### ISSUE TITLE
Call UI

### ISSUE THREAD

**Issue by aubymori** [XYZenix/DTM-17#1]
The call UI is still the UI from 2016/DTM-16.
![2016 Call UI](https://user-images.githubusercontent.com/44238627/179058541-dbe4c68e-2202-4a62-a005-76e2484e6d52.png)
Here's what it looked like in 2017-2019.
![2017 Call UI](https://support.discord.com/hc/article_attachments/1500013905841/callexample.gif)

**Comment by aubymori** [comment]
Might work on this.

**Comment by XYZenix** [comment]
> All issues should go here (and please use the dtm-17 label) -> https://github.com/XYZenix/XYZenixThemes/issues
